Add support for aarch64 (linux, mac), eclipse updated to 2022-01
BlackBeltTechnology/judo-eclipse-zulu-jdk pull request #4
Opened 2022-02-03 12:18 UTC by robertcsakany

2022-02-03 12:27 UTC, noherczeg approved these changes

2022-02-03 12:31 UTC, rolandknobloch requested changes

2022-02-03 12:31 UTC, rolandknobloch commented on hu.blackbelt.judo.eclipse.jdk.zulu.linux.aarch64/src/main/template/META-INF/p2.inf
> +org.eclipse.equinox.p2.touchpoint.eclipse.setJvm(jvm:null);
line break missing

2022-02-03 12:31 UTC, rolandknobloch commented on hu.blackbelt.judo.eclipse.jdk.zulu.macosx.aarch64/src/main/template/Contents/Info.plist
> +</plist>
line break missing

2022-02-03 12:31 UTC, rolandknobloch commented on hu.blackbelt.judo.eclipse.jdk.zulu.macosx.aarch64/src/main/template/META-INF/p2.inf
> +org.eclipse.equinox.p2.touchpoint.eclipse.setJvm(jvm:null);
line break missing

2022-02-03 12:45 UTC, rolandknobloch approved these changes

2022-02-04 14:50 UTC, fruska approved these changes

2022-02-04 20:27 UTC, merged